# Generated by Django 5.2.4 on 2026-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыт"), ("closed", "Закрыт")],
                        default="open",
                        max_length=6,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
